### ISSUE TITLE
Not Working on Ubuntu 12.10 and Chrome 22.

### ISSUE THREAD

**Issue by sudhirkhanger** [tualatrix/LinuxNativeNotification#10]
Title says it all. It is not working anymore in Ubuntu Quantal or stable Chrome.

Thanks.

**Comment by fcsonline** [comment]
Did you try to restart your Google Chrome before start use it? It works for me in Ubuntu 12.10 & and Chrome 23. The only issue I see is that the icon is not shown.

**Comment by sudhirkhanger** [comment]
It is working now on Ubuntu 12.10 and Chrome 23.0.1271.95. Thank you.
