### ISSUE TITLE
Can not handle partial image URLs

### ISSUE THREAD

**Issue by mjohnson9** [tualatrix/LinuxNativeNotification#4]
When a partial URL is given to `window.webkitNotifications.createNotification` for the image, the notification fails to display.

This can be tested by doing the following:
1. Go to [Google](https://www.google.com/)
2. Run `window.webkitNotifications.createNotification("/intl/en_ALL/images/logos/images_logo_lg.gif", "Title", "Body").show();`

I would expect it to display a notification with a title of `Title` and a body of `Body` and the image to be ![Google Images Logo](https://www.google.com/intl/en_ALL/images/logos/images_logo_lg.gif)

**Comment by tualatrix** [comment]
Hi, 

I tried to run the script in JavaScript console when I loaded the Google home page, but it showed:

> window.webkitNotifications.createNotification("/intl/en_ALL/images/logos/images_logo_lg.gif", "Title", "Body").show();
> TypeError: Object false has no method 'show'
> 
> window.webkitNotifications.createNotification("/intl/en_ALL/images/logos/images_logo_lg.gif", "Title",'body')
> false
> 
> window.webkitNotifications.checkPermission()
> 1
> 
> window.webkitNotifications.requestPermission();
> undefined

Do you have any idea?

**Comment by mjohnson9** [comment]
Odd. I'll try it again on a clean install of Chrome in a little bit.

I'm running Google Chrome stable (18.0.1025.168) on Ubuntu 12.04 and version 1.0.1 of the plugin.

**Comment by mjohnson9** [comment]
After cleaning my install of Chrome, the same thing still happens.

![Screenshot](http://dl.dropbox.com/u/3166522/screenshots/Screenshot%20from%202012-05-24%2007%3A18%3A20.png)

**Comment by tualatrix** [comment]
Thanks, I can reproduce this issue. I will work on this to make it work.

**Comment by tualatrix** [comment]
Hello, I've already fixed this issue. Please update your extension and verify if it is fixed.

**Comment by mjohnson9** [comment]
It does seem to be fixed unless you remove the / at the beginning of the URL.

**Comment by tualatrix** [comment]
I didn't remove the "/" in the URL, but joined the "host name" and "url path", didn't it work?

**Comment by mjohnson9** [comment]
Indeed, it does work with a leading slash. But when you remove the leading slash, it no longer works.

**Comment by tualatrix** [comment]
Hi, with the latest update: 1.0.3, I've make it work without leading slash in iconUrl. Please try again.

**Comment by mjohnson9** [comment]
Yep. Works as expected now. Thanks! :)
